### ISSUE TITLE
AWS deployment issue

### ISSUE THREAD

**Issue by manuel1507** [daniel-woods/bodoni-alexa-skill#1]
Hi,

I followed your instructions to deploy the skill, but I got some errors. Following the log from AWS pipeline. It seems to be correlated with DB access. Thanks for any hint.

BR,
Manuel

1 | [Container] 2020/11/14 14:11:01 Waiting for agent ping
-- | --
2 | [Container] 2020/11/14 14:11:03 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2020/11/14 14:11:04 Phase is DOWNLOAD_SOURCE
4 | [Container] 2020/11/14 14:11:04 CODEBUILD_SRC_DIR=/codebuild/output/src521125738/src
5 | [Container] 2020/11/14 14:11:04 YAML location is /codebuild/output/src521125738/src/buildspec.yml
6 | [Container] 2020/11/14 14:11:04 Found possible syntax errors in buildspec:
7 | In the section artifacts
8 | The following keys cannot be identified:
9 | type
10 | [Container] 2020/11/14 14:11:04 Processing environment variables
11 | [Container] 2020/11/14 14:11:04 No runtime version selected in buildspec.
12 | [Container] 2020/11/14 14:11:04 Moving to directory /codebuild/output/src521125738/src
13 | [Container] 2020/11/14 14:11:04 Registering with agent
14 | [Container] 2020/11/14 14:11:04 Phases found in YAML: 3
15 | [Container] 2020/11/14 14:11:04  INSTALL: 2 commands
16 | [Container] 2020/11/14 14:11:04  PRE_BUILD: 4 commands
17 | [Container] 2020/11/14 14:11:04  BUILD: 2 commands
18 | [Container] 2020/11/14 14:11:04 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
19 | [Container] 2020/11/14 14:11:04 Phase context status code:  Message:
20 | [Container] 2020/11/14 14:11:04 Entering phase INSTALL
21 | [Container] 2020/11/14 14:11:04 Running command pip install --upgrade pip
22 | Collecting pip
23 | Downloading https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl (1.5MB)
24 | Installing collected packages: pip
25 | Found existing installation: pip 19.3.1
26 | Uninstalling pip-19.3.1:
27 | Successfully uninstalled pip-19.3.1
28 | Successfully installed pip-20.2.4
29 |  
30 | [Container] 2020/11/14 14:11:12 Running command pip install --upgrade awscli
31 | Collecting awscli
32 | Downloading awscli-1.18.178-py2.py3-none-any.whl (3.4 MB)
33 | Collecting botocore==1.19.18
34 | Downloading botocore-1.19.18-py2.py3-none-any.whl (6.8 MB)
35 | Requirement already satisfied, skipping upgrade: rsa<=4.5.0,>=3.1.2; python_version != "3.4" in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from awscli) (4.5)
36 | Requirement already satisfied, skipping upgrade: s3transfer<0.4.0,>=0.3.0 in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from awscli) (0.3.3)
37 | Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from awscli) (0.15.2)
38 | Requirement already satisfied, skipping upgrade: colorama<0.4.4,>=0.2.5; python_version != "3.4" in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from awscli) (0.4.3)
39 | Requirement already satisfied, skipping upgrade: PyYAML<5.4,>=3.10; python_version != "3.4" in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from awscli) (5.3.1)
40 | Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.1 in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from botocore==1.19.18->awscli) (2.8.0)
41 | Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from botocore==1.19.18->awscli) (0.9.5)
42 | Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.25.4; python_version != "3.4" in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from botocore==1.19.18->awscli) (1.25.10)
43 | Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from rsa<=4.5.0,>=3.1.2; python_version != "3.4"->awscli) (0.4.8)
44 | Requirement already satisfied, skipping upgrade: six>=1.5 in /root/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.19.18->awscli) (1.15.0)
45 | Installing collected packages: botocore, awscli
46 | Attempting uninstall: botocore
47 | Found existing installation: botocore 1.17.50
48 | Uninstalling botocore-1.17.50:
49 | Successfully uninstalled botocore-1.17.50
50 | Attempting uninstall: awscli
51 | Found existing installation: awscli 1.18.127
52 | Uninstalling awscli-1.18.127:
53 | Successfully uninstalled awscli-1.18.127
54 | ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
55 |  
56 | We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
57 |  
58 | boto3 1.14.50 requires botocore<1.18.0,>=1.17.50, but you'll have botocore 1.19.18 which is incompatible.
59 | Successfully installed awscli-1.18.178 botocore-1.19.18
60 |  
61 | [Container] 2020/11/14 14:11:17 Phase complete: INSTALL State: SUCCEEDED
62 | [Container] 2020/11/14 14:11:17 Phase context status code:  Message:
63 | [Container] 2020/11/14 14:11:17 Entering phase PRE_BUILD
64 | [Container] 2020/11/14 14:11:17 Running command pip install -r lambda/requirements.txt -t lambda/
65 | Collecting ask-sdk-core
66 | Downloading ask_sdk_core-1.15.0-py2.py3-none-any.whl (46 kB)
67 | Collecting botocore
68 | Using cached botocore-1.19.18-py2.py3-none-any.whl (6.8 MB)
69 | Collecting boto3
70 | Downloading boto3-1.16.18-py2.py3-none-any.whl (129 kB)
71 | Collecting ask-sdk-runtime>=1.1.0
72 | Downloading ask_sdk_runtime-1.15.0-py2.py3-none-any.whl (25 kB)
73 | Collecting python-dateutil
74 | Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
75 | Collecting ask-sdk-model>=1.0.0
76 | Downloading ask_sdk_model-1.29.0-py2.py3-none-any.whl (909 kB)
77 | Collecting requests
78 | Downloading requests-2.25.0-py2.py3-none-any.whl (61 kB)
79 | Collecting jmespath<1.0.0,>=0.7.1
80 | Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
81 | Collecting urllib3<1.27,>=1.25.4; python_version != "3.4"
82 | Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
83 | Collecting s3transfer<0.4.0,>=0.3.0
84 | Downloading s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
85 | Collecting six>=1.5
86 | Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
87 | Collecting certifi>=2017.4.17
88 | Downloading certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
89 | Collecting chardet<4,>=3.0.2
90 | Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
91 | Collecting idna<3,>=2.5
92 | Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
93 | Installing collected packages: ask-sdk-runtime, six, python-dateutil, ask-sdk-model, certifi, chardet, idna, urllib3, requests, ask-sdk-core, jmespath, botocore, s3transfer, boto3
94 | ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
95 |  
96 | We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
97 |  
98 | aws-sam-cli 1.1.0 requires boto3>=1.14.23,~=1.14.0, but you'll have boto3 1.16.18 which is incompatible.
99 | aws-sam-cli 1.1.0 requires jmespath~=0.9.5, but you'll have jmespath 0.10.0 which is incompatible.
100 | aws-sam-cli 1.1.0 requires python-dateutil<2.8.1,~=2.6, but you'll have python-dateutil 2.8.1 which is incompatible.
101 | aws-sam-cli 1.1.0 requires requests==2.23.0, but you'll have requests 2.25.0 which is incompatible.
102 | Successfully installed ask-sdk-core-1.15.0 ask-sdk-model-1.29.0 ask-sdk-runtime-1.15.0 boto3-1.16.18 botocore-1.19.18 certifi-2020.11.8 chardet-3.0.4 idna-2.10 jmespath-0.10.0 python-dateutil-2.8.1 requests-2.25.0 s3transfer-0.3.3 six-1.15.0 urllib3-1.26.2
103 | WARNING: Target directory /codebuild/output/src521125738/src/lambda/__pycache__ already exists. Specify --upgrade to force replacement.
104 |  
105 | [Container] 2020/11/14 14:11:22 Running command cd lambda
106 |  
107 | [Container] 2020/11/14 14:11:22 Running command python -m unittest discover . -p "*_test.py"
108 | E/root/.pyenv/versions/3.8.3/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.2', 47752), raddr=('52.119.240.26', 443)>
109 | outcome.errors.clear()
110 | ResourceWarning: Enable tracemalloc to get the object allocation traceback
111 | E/root/.pyenv/versions/3.8.3/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.2', 47754), raddr=('52.119.240.26', 443)>
112 | outcome.errors.clear()
113 | ResourceWarning: Enable tracemalloc to get the object allocation traceback
114 | E/root/.pyenv/versions/3.8.3/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.2', 47756), raddr=('52.119.240.26', 443)>
115 | outcome.errors.clear()
116 | ResourceWarning: Enable tracemalloc to get the object allocation traceback
117 | ..DEBUG:aws_client:DynamoDB Expressions Object
118 | DEBUG:aws_client:{':surname': {'S': 'Hero'}, ':firstname': {'S': 'Sicarius'}, ':department': {'S': 'It'}}
119 | ERROR:skill_handler:An error occurred (AccessDeniedException) when calling the Query operation: User: arn:aws:sts::309531445051:assumed-role/CodeStarWorker-portineria-ToolChain/AWSCodeBuild-1415c665-2df2-4e2a-a650-95f9f5c0d248 is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:eu-west-1:309531445051:table/bodoni-employees/index/surname-firstname-index
120 | Traceback (most recent call last):
121 | File "/codebuild/output/src521125738/src/lambda/ask_sdk_runtime/dispatch.py", line 118, in dispatch
122 | output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
123 | File "/codebuild/output/src521125738/src/lambda/ask_sdk_runtime/dispatch.py", line 182, in __dispatch_request
124 | output = supported_handler_adapter.execute(
125 | File "/codebuild/output/src521125738/src/lambda/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
126 | return handler.handle(handler_input)
127 | File "/codebuild/output/src521125738/src/lambda/ask_sdk_runtime/skill_builder.py", line 155, in <lambda>
128 | "handle": lambda self, handler_input: handle_func(
129 | File "/codebuild/output/src521125738/src/lambda/skill_handler.py", line 77, in meeting_intent_handler
130 | resp = dynamo_interface.query_table_by_gsi(session_attr)
131 | File "/codebuild/output/src521125738/src/lambda/aws_client.py", line 51, in query_table_by_gsi
132 | response = self.client.query(
133 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 357, in _api_call
134 | return self._make_api_call(operation_name, kwargs)
135 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 676, in _make_api_call
136 | raise error_class(parsed_response, operation_name)
137 | botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Query operation: User: arn:aws:sts::309531445051:assumed-role/CodeStarWorker-portineria-ToolChain/AWSCodeBuild-1415c665-2df2-4e2a-a650-95f9f5c0d248 is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:eu-west-1:309531445051:table/bodoni-employees/index/surname-firstname-index
138 | /codebuild/output/src521125738/src/lambda/ask_sdk_runtime/dispatch.py:133: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.2', 47758), raddr=('52.119.240.26', 443)>
139 | raise e
140 | ResourceWarning: Enable tracemalloc to get the object allocation traceback
141 | F
142 | ======================================================================
143 | ERROR: test_query_table_by_gsi (aws_client_test.BodoniDynamoHelper)
144 | ----------------------------------------------------------------------
145 | Traceback (most recent call last):
146 | File "/codebuild/output/src521125738/src/lambda/aws_client_test.py", line 34, in test_query_table_by_gsi
147 | resp = self.sample_query()
148 | File "/codebuild/output/src521125738/src/lambda/aws_client_test.py", line 26, in sample_query
149 | resp = dynamo_interface.query_table_by_gsi(input_data)
150 | File "/codebuild/output/src521125738/src/lambda/aws_client.py", line 51, in query_table_by_gsi
151 | response = self.client.query(
152 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 357, in _api_call
153 | return self._make_api_call(operation_name, kwargs)
154 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 676, in _make_api_call
155 | raise error_class(parsed_response, operation_name)
156 | botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Query operation: User: arn:aws:sts::309531445051:assumed-role/CodeStarWorker-portineria-ToolChain/AWSCodeBuild-1415c665-2df2-4e2a-a650-95f9f5c0d248 is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:eu-west-1:309531445051:table/bodoni-employees/index/surname-firstname-index
157 |  
158 | ======================================================================
159 | ERROR: test_send_alert_to_phone (aws_client_test.BodoniDynamoHelper)
160 | ----------------------------------------------------------------------
161 | Traceback (most recent call last):
162 | File "/codebuild/output/src521125738/src/lambda/aws_client_test.py", line 49, in test_send_alert_to_phone
163 | dynamo_resp = self.sample_query()
164 | File "/codebuild/output/src521125738/src/lambda/aws_client_test.py", line 26, in sample_query
165 | resp = dynamo_interface.query_table_by_gsi(input_data)
166 | File "/codebuild/output/src521125738/src/lambda/aws_client.py", line 51, in query_table_by_gsi
167 | response = self.client.query(
168 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 357, in _api_call
169 | return self._make_api_call(operation_name, kwargs)
170 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 676, in _make_api_call
171 | raise error_class(parsed_response, operation_name)
172 | botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Query operation: User: arn:aws:sts::309531445051:assumed-role/CodeStarWorker-portineria-ToolChain/AWSCodeBuild-1415c665-2df2-4e2a-a650-95f9f5c0d248 is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:eu-west-1:309531445051:table/bodoni-employees/index/surname-firstname-index
173 |  
174 | ======================================================================
175 | ERROR: test_send_email (aws_client_test.BodoniDynamoHelper)
176 | ----------------------------------------------------------------------
177 | Traceback (most recent call last):
178 | File "/codebuild/output/src521125738/src/lambda/aws_client_test.py", line 65, in test_send_email
179 | dynamo_resp = self.sample_query()
180 | File "/codebuild/output/src521125738/src/lambda/aws_client_test.py", line 26, in sample_query
181 | resp = dynamo_interface.query_table_by_gsi(input_data)
182 | File "/codebuild/output/src521125738/src/lambda/aws_client.py", line 51, in query_table_by_gsi
183 | response = self.client.query(
184 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 357, in _api_call
185 | return self._make_api_call(operation_name, kwargs)
186 | File "/codebuild/output/src521125738/src/lambda/botocore/client.py", line 676, in _make_api_call
187 | raise error_class(parsed_response, operation_name)
188 | botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Query operation: User: arn:aws:sts::309531445051:assumed-role/CodeStarWorker-portineria-ToolChain/AWSCodeBuild-1415c665-2df2-4e2a-a650-95f9f5c0d248 is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:eu-west-1:309531445051:table/bodoni-employees/index/surname-firstname-index
189 |  
190 | ======================================================================
191 | FAIL: test_response (skill_handler_test.MeetingIntent)
192 | ----------------------------------------------------------------------
193 | Traceback (most recent call last):
194 | File "/codebuild/output/src521125738/src/lambda/skill_handler_test.py", line 47, in test_response
195 | self.assertEqual(expected_response, result["response"])
196 | AssertionError: {'out[32 chars]ml': "<speak>Sorry, I wasn't able to find an e[186 chars]True} != {'out[32 chars]ml': '<speak>Sorry, there was some problem. Pl[171 chars]alse}
197 | Diff is 889 characters long. Set self.maxDiff to None to see it.
198 |  
199 | ----------------------------------------------------------------------
200 | Ran 6 tests in 0.195s
201 |  
202 | FAILED (failures=1, errors=3)
203 | START: BodoniDynamoHelper
204 | START: BodoniDynamoHelper
205 | START: BodoniDynamoHelper
206 | START: HelpIntent
207 | Response:
208 | {
209 | "version": "1.0",
210 | "sessionAttributes": {},
211 | "userAgent": "ask-python/1.15.0 Python/3.8.3",
212 | "response": {
213 | "outputSpeech": {
214 | "type": "SSML",
215 | "ssml": "<speak>This skill can allow you to check into meetings. To do so, please tell me who you have a meeting with.</speak>"
216 | },
217 | "card": {
218 | "type": "Simple",
219 | "title": "Bodoni University",
220 | "content": "This skill can allow you to check into meetings. To do so, please tell me who you have a meeting with."
221 | },
222 | "reprompt": {
223 | "outputSpeech": {
224 | "type": "SSML",
225 | "ssml": "<speak>This skill can allow you to check into meetings. To do so, please tell me who you have a meeting with.</speak>"
226 | }
227 | },
228 | "shouldEndSession": false
229 | }
230 | }
231 | END: HelpIntent
232 | START: LaunchRequest
233 | Response:
234 | {
235 | "version": "1.0",
236 | "sessionAttributes": {
237 | "last_request": {
238 | "retry_title": "Welcome to Bodoni University",
239 | "retry_speech": "How can I help?"
240 | }
241 | },
242 | "userAgent": "ask-python/1.15.0 Python/3.8.3",
243 | "response": {
244 | "outputSpeech": {
245 | "type": "SSML",
246 | "ssml": "<speak>Welcome to Bodoni University. How can I help?</speak>"
247 | },
248 | "card": {
249 | "type": "Simple",
250 | "title": "Welcome to Bodoni University",
251 | "content": "Welcome to Bodoni University. How can I help?"
252 | },
253 | "shouldEndSession": false
254 | }
255 | }
256 | END: LaunchRequest
257 | START: MeetingIntent
258 | Response:
259 | {
260 | "version": "1.0",
261 | "sessionAttributes": {
262 | "company": "google",
263 | "employee": "sicarius",
264 | "last_request": {
265 | "card": "Meeting",
266 | "speech": "Thanks Dan! Do you know sicarius's last name and which department they are from?"
267 | },
268 | "customer": "Dan",
269 | "department": "it",
270 | "employee_last_name": "hero"
271 | },
272 | "userAgent": "ask-python/1.15.0 Python/3.8.3",
273 | "response": {
274 | "outputSpeech": {
275 | "type": "SSML",
276 | "ssml": "<speak>Sorry, there was some problem. Please try again!</speak>"
277 | },
278 | "reprompt": {
279 | "outputSpeech": {
280 | "type": "SSML",
281 | "ssml": "<speak>Sorry, there was some problem. Please try again!</speak>"
282 | }
283 | },
284 | "shouldEndSession": false
285 | }
286 | }
287 |  
288 | [Container] 2020/11/14 14:11:23 Command did not exit successfully python -m unittest discover . -p "*_test.py" exit status 1

**Comment by manuel1507** [comment]
BTW, no issues with the IAM Policy Simulator
<img width="685" alt="Cattura" src="https://user-images.githubusercontent.com/42934442/99159586-d1895b80-26dd-11eb-9468-9211f642a285.PNG">

**Comment by manuel1507** [comment]
Hi,
it seems I manged to solve the issue, but I miss the DB structure. I get errors on the query now:

botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Query key condition not supported

Any help would be really appreciated.

BR,
manuel

**Comment by manuel1507** [comment]
All deployment issues solved. Had to play around with IAM, DynamoDB and Stacks...but finally it works.
